### ISSUE TITLE
[Suggestion] Ability to filter a page by fields other than the default and grouped fields

### ISSUE THREAD

**Issue by qwirksilver** [joyrider3774/Playnite_html_exporter#10]
Similar to [my other suggestion](https://github.com/joyrider3774/Playnite_html_exporter/issues/9) (same use case), it would be great to be able to use the filters that are available in the table view to filter on any available field instead of just the default and grouped fields. This way, I can easily drill down to games that fit criteria I'm looking for. Thanks!!

**Comment by joyrider3774** [comment]
Its the same thing, you'll need to modify the templates as i explained in the other issue if you want to add change the fields displayed and the fields you can filter on. It's not that hard todo but it will be for all pages only the groupfield will change on each page but you can change the default fields.
