### ISSUE TITLE
[Suggestion] Support for exporting data from plugins

### ISSUE THREAD

**Issue by BloodShed-Oni** [joyrider3774/Playnite_html_exporter#12]
Would be possible to add support for other Playnite plugins?

Examples:
Success Story - Show achievements.
Game Activity - Show playtime statistics.
Screenshot Visualizer - Show screenshots from games.

**Comment by joyrider3774** [comment]
Won't happen, too much work and i don't even use those plugins. Sorry i want to keep it basic
