### ISSUE TITLE
[Suggestion] Hide game Title from Cover option

### ISSUE THREAD

**Issue by TobseF** [joyrider3774/Playnite_html_exporter#14]
I like the covers without the title - like on Steam.
So I removes the covers in the template with an additional CSS line:
```css
figcaption{
  visibility: hidden;
}
```
I also tried to remove the `figcaption` element at all. But this breaks the our nice search widget.
I changed it in the tempalte: `Templates\default\page.txt`. But maybe this is also useful for others.
So we could add an option in the export section to hide the title. Or even add a dynamic option to toggle the title visibility.

<img width="693" alt="before" src="https://user-images.githubusercontent.com/1190109/195950099-bab0f66f-9a21-470f-824d-15de2939b012.png">

<img width="693" alt="after" src="https://user-images.githubusercontent.com/1190109/195950116-36f2c1a6-9c2c-4c73-b5cf-22e5db7c9fa7.png">

**Comment by joyrider3774** [comment]
You can create your own templates in the data directory of the plugin. If you copy an original (template) folder from the installation folder, rename the folder to some new name and then in settings of the addon select your custom folder as the template it will always use your template with whatever you changed plus it won't get overwritten when i would update the plugin. I'm not going to add such setting, the whole point of the templates is to be able to create your own or your own based on the default ones by editing the templates
