### ISSUE TITLE
Wiped out my drive

### ISSUE THREAD

**Issue by Nightchanger** [joyrider3774/Playnite_html_exporter#15]
Just used to add my library to display on my disk on key.
I forgot to add a new folder for it. and told to dump the disk on the key.
It wiped my files, thankfully I backed up most of my files. except for a personal scripting project for my password manager.
Hope you can look into fixing it.

**Comment by joyrider3774** [comment]
What do you mean with "disk on key" ? And did you like select just the drive and not a folder ?
