### ISSUE TITLE
Shrink images and remove duplicates to save disc space

### ISSUE THREAD

**Issue by TobseF** [joyrider3774/Playnite_html_exporter#2]
My exported library takes about 4.42 GB. I like the cover view, but it needs 1264 MB to load the site. Not the best size, so load it on your mobile. So it would be great it the plugin could also shrink the image files during export. Because of different libs, I also have duplicate games. To have two images for the same game, can also be avoided.

I wrote a small Script which can already to this for you:

### 👉 Sample Game Lib: [games.tobse.eu](http://games.tobse.eu)
|      | Before  | After
|----- | --------|-------
|Size  | 4.42 GB | 466 MB
|Files |    8875 |   8210

But to have this available as an option would be a much better approach.

Thank you for your great plugin.

**Comment by joyrider3774** [comment]
hey just to let you know i'm working on it, this is what i got so far not sure if you'll get same output with my new upcomming version. At which % jpeg quality are those numbers from ?

![image](https://user-images.githubusercontent.com/10714776/130320764-43340bb3-6135-49aa-b10a-c48090345081.png)

**Comment by TobseF** [comment]
Great, that will make the export much more straight forward. As you can see in my script, I converted background and coder into jpeg. The logos were were more difficult. Because they often contain text with transparent backgrounds, I converted them into png. For .ico files this was tricky and required a seconds step to, get the layer with the highest resolution. In addition I used the game name as key and mapped it to the first image to avoid duplicated images for the same game (on different platforms). This saved 665 files.

My numbers are a little bit cheated. I converted them with 100% jpg quality and after that I shrank them with a content based jpg image minifier JPGMini. But I will test your version asp I get the update.

Thank you, for maintaining the Playnite_html_exporter.

**Comment by joyrider3774** [comment]
How long does your version run ?
Also when you say duplicates you mean also duplicate games ? I had not thought of that before that this could happen and have currently nothing implemented for this.

I also added parralel runs of imagemagick and only convert files if they are not already in the target filetype but this does not shave of many size (depending on your setup). But i just added a force option so that it force converts again even if filetype is the same

For ico files i saw it also but i managed to find an image magick script that can do it one call to imagemagick (it also takes biggest image in resolution from the ico)

here is an example call to convert ico to png in one call
```
magick.exe I:\games\Playnite\library\files\2a6f1778-483f-4bcc-b4f9-5a2f0fb9c07d\ce031fdb-e532-40a5-ae07-2534e2b6888d.ico ( -clone 0--1 -layers Merge ) -channel A -evaluate Multiply "%[fx: w == u[-1].w ? 1 : 0] %"  +channel +delete -background None -layers merge I:\Playnite_HTML_Export\grid\2a6f1778-483f-4bcc-b4f9-5a2f0fb9c07d\ce031fdb-e532-40a5-ae07-2534e2b6888d.png`
```

**Comment by joyrider3774** [comment]
here are latest results, i'm nearly finished with it. No Force means that if original image is already in target file type it will just copy it. Force means if original image is already in target file type it will resave it (with applied jpeg quality) the nr 85 & 100 at the end is the jpeg quality. Resize parameters were 48x48 for icon, 180x270 for cover and 1280x720 for backgrounds. When resizing it will only resize if original image is bigger and always after all (resize / reencode) work it will check if original image was smaller and if so copy orginal image back
![image](https://user-images.githubusercontent.com/10714776/130352172-d67fdb0f-9837-48b2-89da-8d52d3d260e8.png)

**Comment by joyrider3774** [comment]
Still need to find some time to remove duplicate images

**Comment by joyrider3774** [comment]
@TobseF i released an initial version with options for resizing and converting, no duplicate removal yet, i might do that in another version in the future. If you could try it out and let me know your findings thanks. https://github.com/joyrider3774/Playnite_html_exporter/releases/tag/V2.0

**Comment by joyrider3774** [comment]
image deduplication got added in 2.1 check https://github.com/joyrider3774/Playnite_html_exporter/releases/tag/V2.1
