### ISSUE TITLE
[Suggestion] Only export games matching playnite filter

### ISSUE THREAD

**Issue by BloodShed-Oni** [joyrider3774/Playnite_html_exporter#4]
Add an option to only export games matching the filter settings in playnite.

Example:
- Installed games only.
- Favorite and installed games only
- Games filtered by tags

**Comment by joyrider3774** [comment]
Hey this is a good idea, i'm working on it. But currently images are never deleted when exporting, it only erased html files, so i'll add a new option to erase the output folder as well so you only have the data (including images) from the filtered games.

**Comment by joyrider3774** [comment]
done in just released version 3.3
