### ISSUE TITLE
[Suggestion] Option to only export the index

### ISSUE THREAD

**Issue by PescheHelfer** [joyrider3774/Playnite_html_exporter#5]
If this isn't already possible: Could you add an option to only export the index, without the separate detail pages for each game? 

Use case: I would mainly use the export to quickly check during a sale if I already own the game or not, when playnite is not available (different computer, only mobile available, ...). For that, the index is sufficient for me.

Thanks for considering this and thanks for this excellent plug in !

**Comment by luxzg** [comment]
+1 to this

I am trying now to do this with template modifications but without success, seems that whenever `%gamecards%` is run all the individual HTMLs get created.

I emptied the `"gamedetails.txt"` of my custom template, so at least export is quick, probably close to same as if individual details pages aren't created at all. It does create 2700+ empty files though.

**Comment by luxzg** [comment]
[luxzg.zip](https://github.com/joyrider3774/Playnite_html_exporter/files/8557296/luxzg.zip)
@PescheHelfer : I think I have finished this simplified template of mine. I am attaching it here for you in case you want to try. 
Takes under 2 seconds to generate for 2700+ games, and you can delete/ignore the individual files, and use only `index.html`
I am also attaching an example screenshot of my own library.
![Snap 2022-04-25 at 21 07 03](https://user-images.githubusercontent.com/9318107/165157266-2cc7cbad-6f61-454b-9823-f6679b680724.png)
Please note that I've removed all links except the quick A-Z quick links, changed few columns, and made some other minor changes to suite my own use. But seems like we aim for mostly the same thing, so this should be good base for you to further modify if you need.

**Comment by PescheHelfer** [comment]
Great, thanks a lot! I'll give that a try.

**Comment by joyrider3774** [comment]
The plugin always generates the detailpages whenever it handles the 1st page not sure i can disable it have not looked into that yet but i could potentially check for an empty template file and not generate them then

**Comment by joyrider3774** [comment]
Hey i added this option, well basically if gamedetails.txt of the template you had chosen for the 1st page is empty it will not generate the game html pages anymore. It will be released soon

**Comment by PescheHelfer** [comment]
Excellent, thanks a lot!
