### ISSUE TITLE
[Suggestion] Option to change which columns are shown in the list and table views

### ISSUE THREAD

**Issue by qwirksilver** [joyrider3774/Playnite_html_exporter#9]
Hi there! I'm loving this extension - thank you! I have found myself really wishing the displayed columns showed different data. The default generated columns are all pretty much useless for my use case. Ideally, I'd be able to choose the columns that display, but at minimum I'd like to show the columns that correspond to all of the grouping I've used for my pages.

For instance, my use case is helping my friends see which games we can play together. I'd love for them to be able to look at the page that's grouped by Feature to find multiplayer games, then to be able to see the Genre or other data in the table/list so that they can try to find something they feel like playing.

Thanks again!

**Comment by joyrider3774** [comment]
Hi this is not possible and certainly not possible to define this per page. you can however make a copy of the templates folder and place it inside the plugins data folder and give the subfolders a new name (so it does not conflict with default provided names). Then you can modify the templates and change which values will always be shown (besides the groupfield) by changing the template. However this will be a choice for all pages generated not just a single page. You could add extra columns as well change the data displayed.

These are the values you can use :
https://github.com/joyrider3774/Playnite_html_exporter/blob/main/HtmlExporterPlugin.cs#L1773

if it says `CurrentGameValuesDict["gamename"] = HttpUtility.HtmlEncode(realgame.Name);` you can write `%gamename%` in the templates to let it display game name.

Be aware generated amount of (html) columns and actual rows showing column data need to match to so will need to change multiple files the template to match this.

Once you have created such "customn" templates you can restart playnite and in the settings choose your own made template per page, you will have to do this manually for each page though but it's only a one time setup.

I never documented creating your own templates but it is certainly possible and the system is designed to do so.

besides that, i'm leaving the issue open i might be able to define an extra customn field per page to display to let you choose a field you want to display but that requires much more changes and i might or might not do them eventually in the future.

**Comment by qwirksilver** [comment]
Thank you for the guidance! So, I actually tried this but the issue I was having was that I can't actually get any data to show in the gamecard rows. I'll explain, but I understand you may not want/be able to help.

(I tried this with the list and table views with the same results, but I'll explain with the list view.)

- **Template**: default list combobox quicklinks
- **File**: gamecard.txt
- **Edit**: added `<TD><a href="%genre_filename%#quicklink-%genre%">%genre%</a></TD>`
- **Result**: Column was added properly (I also added the header and adjusted the colspan in the relevant files), but no data appeared in the column. Here's a test entry for Escape Simulator, which definitely has genre data. Note how nothing appears in the new "Genre" column at the right:
![image](https://user-images.githubusercontent.com/13282342/177045832-3282126d-362a-4468-a8ed-d559d098a11b.png)
![image](https://user-images.githubusercontent.com/13282342/177045835-f1d6b2b6-20b4-4b38-b6ba-12cdf8eec3a0.png)

### Troubleshooting
Here are some other things I tried:
- I noticed that the gamedetails.txt file uses `%genres%` instead of `%genre%`, so I tried to change the edit to `<TD><a href="%genre_filename%#quicklink-%genre%">%genres%</a></TD>`. However, this just printed the string "%genres%" into the rows:
![image](https://user-images.githubusercontent.com/13282342/177045890-50a23873-e259-4300-8a15-83f5d0996610.png)
- I tried to fill in different data that wasn't multi-lined just in case, so I tried `%version%` instead of `%genre%`. That also resulted in blank data.
- I replaced `%genre%` with `%platform%` since I knew the platform data was available, and that worked as expected:
![image](https://user-images.githubusercontent.com/13282342/177045991-f7dfffd1-5371-43b5-b8b3-1691d8f30d2c.png)


So, I am just not sure how to actually access the data/get it to show up in the rows. Thanks again for all of your help!

**Comment by joyrider3774** [comment]
Hi,

Its actually a bug i only fill those fields if they are the groupfield for that page, i will try to fix it. But be aware those fields can contain multiple data and i will show them comma seperated if they are not the groupfield. when they are the groupfield i actually make sure the game is duplicated and only shows one entry for each item in their lists but when the field is not the groupfield this will not be possible and the only way around that that is to display all possible items from the list comma seperated as a string.

**Comment by joyrider3774** [comment]
Hi @qwirksilver,

I just released a new version that fills up those fields (genre, category etc) even when they are not the groupfield. But they are as i previously said a comma seperated text, so you won't be able to drill down for example on genre if they contain multiple values

**Comment by qwirksilver** [comment]
Finally had a chance to try out the new version and it's working great. Thank you again! 😸
